In [5]:
import numpy as np

tableau_de_zeros = np.zeros((5, 10))

print(tableau_de_zeros)



[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [6]:

import numpy as np

# Exemple de création d'une grille (tableau NumPy)
largeur, hauteur = 5, 5
grille = np.zeros((largeur, hauteur), dtype=int)  # Initialisation avec des cases vides (0)

x, y = 2, 2  # Position à scanner

# Scanner les éléments autour de la position (x, y)
for i in range(-1, 2):
    for j in range(-1, 2):
        if 0 <= x + i < largeur and 0 <= y + j < hauteur:
            # Vous pouvez maintenant accéder à la case grille[x+i][y+j] pour l'examiner
            print(f"Élément à la position ({x + i}, {y + j}): {grille[x + i, y + j]}")


Élément à la position (1, 1): 0
Élément à la position (1, 2): 0
Élément à la position (1, 3): 0
Élément à la position (2, 1): 0
Élément à la position (2, 2): 0
Élément à la position (2, 3): 0
Élément à la position (3, 1): 0
Élément à la position (3, 2): 0
Élément à la position (3, 3): 0


In [8]:
import numpy as np

# Créez l'aquarium initial avec des zéros.
aquarium = np.zeros((5, 10), dtype=int)

# Fonction pour afficher l'aquarium.
def afficher_aquarium():
    for ligne in aquarium:
        for case in ligne:
            if case == 0:
                print(" ", end=" ")
            else:
                print("1", end=" ")
        print()

# Fonction pour ajouter un poisson à une position donnée.
def ajouter_poisson(x, y):
    if 0 <= x < 5 and 0 <= y < 10:
        aquarium[x, y] = 1

# Fonction pour déplacer tous les poissons vers le bas.
def deplacer_poissons():
    for i in range(4, -1, -1):
        for j in range(10):
            if aquarium[i, j] == 1:
                aquarium[i, j] = 0
                if i < 4:
                    aquarium[i + 1, j] = 1

# Exemple d'utilisation :
ajouter_poisson(2, 5)  # Ajoutez un poisson à la position (2, 5).
afficher_aquarium()    # Affichez l'aquarium.
deplacer_poissons()    # Déplacez les poissons vers le bas.
print("Après déplacement :")
afficher_aquarium()    # Affichez l'aquarium après le déplacement.


                    
                    
          1         
                    
                    
Après déplacement :
                    
                    
                    
          1         
                    
