In [5]:
import numpy as np

tableau_de_zeros = np.zeros((5, 10))

print(tableau_de_zeros)

tableau_de_zeros[0] = 1
tableau_de_zeros[2][3] = 1


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [6]:

import numpy as np

# Exemple de création d'une grille (tableau NumPy)
largeur, hauteur = 5, 5
grille = np.zeros((largeur, hauteur), dtype=int)  # Initialisation avec des cases vides (0)

x, y = 2, 2  # Position à scanner

# Scanner les éléments autour de la position (x, y)
for i in range(-1, 2):
    for j in range(-1, 2):
        if 0 <= x + i < largeur and 0 <= y + j < hauteur:
            # Vous pouvez maintenant accéder à la case grille[x+i][y+j] pour l'examiner
            print(f"Élément à la position ({x + i}, {y + j}): {grille[x + i, y + j]}")


Élément à la position (1, 1): 0
Élément à la position (1, 2): 0
Élément à la position (1, 3): 0
Élément à la position (2, 1): 0
Élément à la position (2, 2): 0
Élément à la position (2, 3): 0
Élément à la position (3, 1): 0
Élément à la position (3, 2): 0
Élément à la position (3, 3): 0
